### PR TITLE
English localization

### PR DESCRIPTION
**Pull request by veroxzik**
English localization for GUI and tooltips.
Default is Japanese, will switch to English when Windows display language is set to English.
--- (google translate) ---
英訳。
日本語はデフォルトです。Windowsの表示オプションが英語の場合、英語が始まります。

### CODE REVIEW

**Comment by paralleltree** [comment]
Thank you very much for the pr!
I'll check and merge it later XD

**Comment by paralleltree** [comment]
seeing the changes, I think I have to change file filter strings...
can you give me the maintainer permissions for this pr?

**Comment by veroxzik** [comment]
I agree the filter strings are weird-- they were the last thing I did and I wasn't sure how best to handle them.
You should already have permission to edit.

**Comment by paralleltree** [comment]
oh I couldn't push my commits due to my 2FA settings, sorry.
I rewrote the filter strings and replaced remaining Japanese text with `FileFilterStrings.AudioFilter` in `SoundSourceSelector.cs`.
so can you check them?

**Review by paralleltree — APPROVED** [review]

**Comment by veroxzik** [comment]
It looks good to me. Thanks for the updates!

**Comment by paralleltree** [comment]
Okay. I'll merge this after modifying the CI script.

**Pull request merged**
